<link rel="preload" href="fonts/fa-solid-900.woff2" as="font" type="font/woff2" crossorigin="anonymous">
<link rel="preload" href="fonts/SourceSansPro-Bold.otf.woff2" as="font" type="font/woff2" crossorigin="anonymous">
<link rel="preload" href="fonts/SourceSansPro-Light.otf.woff2" as="font" type="font/woff2" crossorigin="anonymous">
<link rel="preload" href="fonts/SourceSansPro-Regular.otf.woff2" as="font" type="font/woff2" crossorigin="anonymous">
<link rel="preload" href="fonts/SourceSansPro-Semibold.otf.woff2" as="font" type="font/woff2" crossorigin="anonymous">
<link rel="preload" href="fonts/sourceserifpro-bold-webfont.woff2" as="font" type="font/woff2" crossorigin="anonymous">
<link rel="preload" href="fonts/sourceserifpro-boldit-webfont.woff2" as="font" type="font/woff2" crossorigin="anonymous">
<link rel="preload" href="fonts/sourceserifpro-it-webfont.woff2" as="font" type="font/woff2" crossorigin="anonymous">
<link rel="preload" href="fonts/sourceserifpro-regular-webfont.woff2" as="font" type="font/woff2" crossorigin="anonymous">
